name: Build airptpd for all supported platforms

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  linux-aarch64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}
          submodules: recursive

      - name: Containerised Build
        run: |
          docker build --build-arg TARGETARCH=linux-aarch64 --output type=local,dest=. .
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: airptpd-linux-aarch64
          path: ${{ github.workspace }}/airptpd-linux-aarch64



  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}
          submodules: recursive

      - name: Containerised Build
        run: |
          docker build --build-arg TARGETARCH=linux-x86_64 --output type=local,dest=. .

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: airptpd-linux-x86_64
          path: ${{ github.workspace }}/airptpd-linux-x86_64


  macos-arm64:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install build dependencies
        run: |
          brew install git autoconf automake libtool pkg-config gettext libevent

      - name: Build for macOS ARM64
        run: |
          export CFLAGS="-I$(brew --prefix)/include"
          export LDFLAGS="-L$(brew --prefix)/lib"

          autoreconf -fi
          ./configure --enable-daemon
          make
          mkdir -p release
          cp src/airptpd release/airptpd-macos-arm64
          chmod +x release/airptpd-macos-arm64

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: airptpd-macos-arm64
          path: release/airptpd-macos-arm64

  macos-x86_64:
    runs-on: macos-15-intel
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install build dependencies
        run: |
          brew install git autoconf automake libtool pkg-config gettext libevent

      - name: Build for macOS x86_64
        run: |
          export CFLAGS="-I$(brew --prefix)/include"
          export LDFLAGS="-L$(brew --prefix)/lib"

          autoreconf -fi
          ./configure --enable-daemon
          make
          mkdir -p release
          cp src/airptpd release/airptpd-macos-x86_64
          chmod +x release/airptpd-macos-x86_64

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: airptpd-macos-x86_64
          path: release/airptpd-macos-x86_64
